version: '3'
services:
  db:
    image: postgres
    container_name: test_task
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CJzk7fvBX7aBd5He
      POSTGRES_DB: test_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"